Todolist
MFahadUmer/todolist pull request #2
Opened 2020-09-23 08:18 UTC by imhilla

Please review this project for JavaScript section of the curriculum.
We added all functionalities required and would wish for great feedback. 
We added:-
- Delete todo function
- Create a project and add task
- Added color functionality

2020-09-23 10:57 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @imhilla and @MFahadUmer! Well done! Your project looks good. There are a few changes to make before moving forward though. These are:
- [ ] Improve your local setup instructions in your `README.md` file. "open index from chrome" is not explicit enough for the user checking your project without prior development knowledge.
- [ ] Making any changes to the app e.g. adding a new project or todo item requires one to refresh the whole page in order to see the changes. Please fix this. The changes should be seen in real-time.
- [ ] __[Optional]__ The forms used to create a project or a todo should have validations, you should not be able to create an empty project/todo
- [ ] Check out the comments in the code below.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-09-23 10:57 UTC, trekab commented on src/task.js
> +  };
Use ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)) for this function declaration.

2020-09-23 10:57 UTC, trekab commented on src/color.js
> +  }
Use ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)) for this function declaration.

2020-09-23 10:57 UTC, trekab commented on src/project.js
> +  }
Use ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)) for this function declaration.

2020-09-24 08:50 UTC, rOluochKe approved these changes
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-09-24 09:01 UTC, merged